In [1]:
import numpy as np
import pandas as pd
import os
import glob as glob

In [2]:
filepath = '/Users/frankanayet/Google Drive/NLineData/Beh_Data/Nline-Space/Space'
os.chdir(filepath)

In [3]:
tmp_db = pd.read_csv('03001.csv')

In [4]:
colnames = tmp_db.columns

In [5]:
colnames

Index([u'ramp_up', u'stim_t', u'runs', u'nLocArm', u'nLoc', u'ntasks',
       u'percentnull', u'tasks', u'flickerFreq', u'flickerPer',
       ...
       u'ITI_StartReal4', u'endRun1', u'endRun2', u'endRun3', u'endRun4',
       u'durRun1', u'durRun2', u'durRun3', u'durRun4', u'endExp'],
      dtype='object', length=695)

In [6]:
filenames = glob.glob('IEM_*.csv')
print filenames

['IEM_03001.csv', 'IEM_03003.csv', 'IEM_03004.csv', 'IEM_03005.csv', 'IEM_03006.csv', 'IEM_03007.csv', 'IEM_03008.csv']

In [7]:
db = pd.DataFrame()
for name in filenames:
    id1 = filenames[0].find('_') + 1
    id2 = filenames[0].find('.')
    sub_nbr = name[id1:id2]
    s_id = 's_'+sub_nbr
    frame = pd.read_csv(name, header=0, index_col=False,names=colnames)
    frame['Subject'] = s_id
    db = pd.concat([db, frame], ignore_index=True)

In [8]:
db.head(40)

,ramp_up,stim_t,runs,nLocArm,nLoc,ntasks,percentnull,tasks,flickerFreq,flickerPer,...,endRun1,endRun2,endRun3,endRun4,durRun1,durRun2,durRun3,durRun4,endExp,Subject
0,16,4,4,3,13,1,0.4,attend stim,6,0.16667,...,2493.6592,2947.0942,3279.8082,3617.7555,268.0087,268.0133,268.0164,268.0028,13-Oct-2015 10:55:02,s_03001
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001
30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001
31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001
33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001
35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001
36,16,4,4,3,13,1,0.4,attend stim,6,0.16667,...,8518.2770,8834.5564,9198.1219,9533.3194,268.0235,268.0120,268.0184,268.0228,26-Oct-2015 16:07:47,s_03003
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03003
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03003
39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03003

In [9]:
db.groupby('Subject')[['hit1','falseAlarm1','correctRejection1','miss1']].mean()

             hit1  falseAlarm1  correctRejection1     miss1
Subject
s_03001  0.423077     0.115385           0.346154  0.115385
s_03003  0.500000     0.038462           0.423077  0.038462
s_03004  0.423077     0.000000           0.461538  0.115385
s_03005  0.423077     0.038462           0.423077  0.115385
s_03006  0.461538     0.000000           0.461538  0.076923
s_03007  0.500000     0.000000           0.461538  0.038462
s_03008  0.538462     0.461538           0.000000  0.000000

In [10]:
db.drop(['Condition1','Condition2','Condition3','Condition4'], axis=1,inplace=True)

In [11]:
db.rename(columns={'Conditon1':'Condition1','Conditon2':'Condition2','Conditon3':'Condition3','Conditon4':'Condition4'},
          inplace=True)

Setup some variables

In [12]:
stim_dur = db.stim_t.loc[0]
ramp_up = db.ramp_up.loc[0]

'null' 1-4 indexes null trials that have to separate for onset creation

In [13]:
db.groupby('Subject')[['null1','null2','null3','null4']].sum()

         null1  null2  null3  null4
Subject
s_03001     10     10     10     10
s_03003     10     10     10     10
s_03004     10     10     10     10
s_03005     10     10     10     10
s_03006     10     10     10     10
s_03007     10     10     10     10
s_03008     10     10     10     10

In [14]:
import string

In [15]:
runs = ['1','2','3','4']
subs = db.Subject.unique()

In [16]:
db[(db['Subject']=='s_03001') & (db['null1'] == 1)]['stim_StartReal1']

5      55.0010
8      74.5019
10     87.0012
12     98.5009
17    135.0010
19    149.0012
22    168.5008
24    183.5014
32    239.5011
35    264.0019
Name: stim_StartReal1, dtype: float64

In [17]:
db[(db['Subject']=='s_03001') & (db['null1'] == 0)]['stim_StartReal1'] -16

0       4.0031
1      10.5015
2      16.5013
3      23.0010
4      31.0018
6      44.5008
7      50.5010
9      64.5013
11     76.5011
13     91.0016
14     96.5021
15    105.0009
16    110.5010
18    127.0009
20    138.5020
21    145.0009
23    160.0008
25    173.5016
26    182.0021
27    188.5011
28    195.0010
29    202.5012
30    210.5010
31    216.0013
33    231.0013
34    239.5015
Name: stim_StartReal1, dtype: float64

In [19]:
nullstr = 'null'
onsetstr = 'stim_StartReal'
path = '/Users/frankanayet/Google Drive/NLineData/Beh_Data/NLine-Space/Space/OnsetFiles_LSS'
if not os.path.exists(path):
    os.makedirs(path)
for s in subs:
    for r in runs:
        run = 'run'+r
        nulltmp = nullstr+r
        onsettmp = onsetstr+r
        tmp = db[(db['Subject']==s) & (db[nulltmp] == 0)][onsettmp] - ramp_up
        tmp_db = pd.DataFrame.from_items([('time',tmp[tmp>=0]),('duration',stim_dur),('val',1)])
        tmp_path = '/Users/frankanayet/Google Drive/NLineData/Beh_Data/NLine-Space/Space/OnsetFiles_LSS_IEM/'+s+'/'
        if not os.path.exists(tmp_path):
            os.makedirs(tmp_path)
        tmp_filename = s+'_'+run+'_AllOnsets.txt'
        tmp_pathfile = tmp_path + tmp_filename
        tmp_db.to_csv(tmp_pathfile, sep='\t', header=False, index=False)

In [18]:
tmp = db[(db['Subject']=='s_03001') & (db['null1'] == 0)]['stim_StartReal1'] - ramp_up
tmp_db = pd.DataFrame.from_items([('time',tmp[tmp>=0]),('duration',stim_dur),('val',1)])
tmp_db

        time  duration  val
0     4.0031         4    1
1    10.5015         4    1
2    16.5013         4    1
3    23.0010         4    1
4    31.0018         4    1
6    44.5008         4    1
7    50.5010         4    1
9    64.5013         4    1
11   76.5011         4    1
13   91.0016         4    1
14   96.5021         4    1
15  105.0009         4    1
16  110.5010         4    1
18  127.0009         4    1
20  138.5020         4    1
21  145.0009         4    1
23  160.0008         4    1
25  173.5016         4    1
26  182.0021         4    1
27  188.5011         4    1
28  195.0010         4    1
29  202.5012         4    1
30  210.5010         4    1
31  216.0013         4    1
33  231.0013         4    1
34  239.5015         4    1