In [1]:
import numpy as np
import pandas as pd
import os
import glob as glob

In [2]:
filepath = '/Users/frankanayet/Google Drive/NLineData/Beh_Data/Nline-Space/Space'
os.chdir(filepath)

In [3]:
tmp_db = pd.read_csv('03001.csv')

In [4]:
colnames = tmp_db.columns

In [5]:
colnames

Index([u'ramp_up', u'stim_t', u'runs', u'nLocArm', u'nLoc', u'ntasks',
       u'percentnull', u'tasks', u'flickerFreq', u'flickerPer',
       ...
       u'ITI_StartReal4', u'endRun1', u'endRun2', u'endRun3', u'endRun4',
       u'durRun1', u'durRun2', u'durRun3', u'durRun4', u'endExp'],
      dtype='object', length=695)

In [6]:
filenames = glob.glob('IEM_*.csv')
print filenames

['IEM_03001.csv', 'IEM_03003.csv', 'IEM_03004.csv', 'IEM_03005.csv', 'IEM_03006.csv', 'IEM_03007.csv', 'IEM_03008.csv']

In [7]:
db = pd.DataFrame()
for name in filenames:
    id1 = filenames[0].find('_') + 1
    id2 = filenames[0].find('.')
    sub_nbr = name[id1:id2]
    s_id = 's_'+sub_nbr
    frame = pd.read_csv(name, header=0, index_col=False,names=colnames)
    frame['Subject'] = s_id
    frame['Trial'] = np.arange(36)
    db = pd.concat([db, frame], ignore_index=True)

In [8]:
db.head(40)

,ramp_up,stim_t,runs,nLocArm,nLoc,ntasks,percentnull,tasks,flickerFreq,flickerPer,...,endRun2,endRun3,endRun4,durRun1,durRun2,durRun3,durRun4,endExp,Subject,Trial
0,16,4,4,3,13,1,0.4,attend stim,6,0.16667,...,2947.0942,3279.8082,3617.7555,268.0087,268.0133,268.0164,268.0028,13-Oct-2015 10:55:02,s_03001,0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001,1
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001,2
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001,3
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001,4
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001,5
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001,6
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001,7
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001,8
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001,9
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001,10
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001,11
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001,12
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001,13
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001,14
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001,15
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001,16
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001,17
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001,18
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001,19
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001,20
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001,21
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001,22
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001,23
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001,24
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001,25
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001,26
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001,27
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001,28
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001,29
30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001,30
31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001,31
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001,32
33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001,33
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001,34
35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03001,35
36,16,4,4,3,13,1,0.4,attend stim,6,0.16667,...,8834.5564,9198.1219,9533.3194,268.0235,268.0120,268.0184,268.0228,26-Oct-2015 16:07:47,s_03003,0
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03003,1
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03003,2
39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s_03003,3

In [9]:
db.groupby('Subject')[['hit1','falseAlarm1','correctRejection1','miss1']].mean()

             hit1  falseAlarm1  correctRejection1     miss1
Subject
s_03001  0.423077     0.115385           0.346154  0.115385
s_03003  0.500000     0.038462           0.423077  0.038462
s_03004  0.423077     0.000000           0.461538  0.115385
s_03005  0.423077     0.038462           0.423077  0.115385
s_03006  0.461538     0.000000           0.461538  0.076923
s_03007  0.500000     0.000000           0.461538  0.038462
s_03008  0.538462     0.461538           0.000000  0.000000

In [10]:
db.drop(['Condition1','Condition2','Condition3','Condition4'], axis=1,inplace=True)

In [11]:
db.rename(columns={'Conditon1':'Condition1','Conditon2':'Condition2','Conditon3':'Condition3','Conditon4':'Condition4'},
          inplace=True)

Setup some variables

In [12]:
rad_deg = db.radDeg.loc[0]
rad_deg

1.5

In [13]:
rad_pix = db.radPix.loc[0]
rad_pix

134.14869999999999

'null' 1-4 indexes null trials that have to separate for onset creation

In [14]:
db.groupby('Subject')[['null1','null2','null3','null4']].sum()

         null1  null2  null3  null4
Subject
s_03001     10     10     10     10
s_03003     10     10     10     10
s_03004     10     10     10     10
s_03005     10     10     10     10
s_03006     10     10     10     10
s_03007     10     10     10     10
s_03008     10     10     10     10

In [15]:
runs = ['1','2','3','4']
subs = db.Subject.unique()

In [16]:
values = db.Condition1.unique()
values.sort()
#values = values[~np.isnan(values)]
values

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
db[(db['Subject']=='s_03001') & (db['null1'] == 0)]['stimLocsX1']

0    -0.97714
1     0.00000
2     2.26130
3     3.26530
4    -2.09910
6     0.00000
7     0.00000
9    -3.46090
11    0.00000
13    0.00000
14    1.43480
15    0.00000
16    0.00000
18    0.00000
20    2.36010
21    0.00000
23   -0.61544
25    0.00000
26    2.75970
27    0.00000
28   -2.90420
29    0.00000
30   -1.79440
31    0.64903
33    0.00000
34    0.00000
Name: stimLocsX1, dtype: float64

In [18]:
db[(db['Subject']=='s_03001') & (db['null1'] == 0)]['stimLocsY1']

0     0.00000
1     2.38560
2     0.00000
3     0.00000
4     0.00000
6    -2.83640
7    -1.68950
9     0.00000
11    0.00000
13   -1.49040
14    0.00000
15    2.91020
16    1.23620
18    1.31060
20    0.00000
21   -0.72205
23    0.00000
25   -1.64670
26    0.00000
27    3.40810
28    0.00000
29    0.00000
30    0.00000
31    0.00000
33    1.97310
34   -3.16850
Name: stimLocsY1, dtype: float64

In [19]:
db[(db['Subject']=='s_03001') & (db['null2'] == 0)][['stimLocsX2', 'stimLocsY2', 'Condition2']]

    stimLocsX2  stimLocsY2  Condition2
1     -1.77030     0.00000           2
2      3.28310     0.00000           6
3     -1.25530     0.00000           3
6      0.00000     3.47640          12
7      2.16810     0.00000           5
8     -2.60450     0.00000           1
9      0.00000    -2.96010           7
10     1.00110     0.00000           4
11     0.00000     1.99360          11
12     0.00000     0.80472          10
13     0.00000    -2.10010           8
15     0.00000    -1.40890           9
16     0.00000     0.00000          13
18     0.00000    -0.51881           9
19     0.00000     1.65710          11
20     0.00000     1.32530          10
23    -0.74206     0.00000           3
26     2.14320     0.00000           5
27     0.00000    -2.01040           8
28     2.91190     0.00000           6
29     0.00000     0.00000          13
30     1.33790     0.00000           4
32    -1.75360     0.00000           2
33    -2.73160     0.00000           1
34     0.00000     2.85770          12
35     0.00000    -2.70120           7

In [36]:
export_data = db[(db['Subject']=='s_03001') & (db['null1'] == 0)][['stimLocsX1', 'stimLocsY1', 'Condition1']]

In [37]:
export_data = np.zeros((len(db[(db['Subject']=='s_03001') & (db['null1'] == 0)][['stimLocsX1', 'stimLocsY1', 'Condition1']])*3,3))

In [38]:
export_data[:26,0:2] = db[(db['Subject']=='s_03001') & (db['null1'] == 0)][['stimLocsX1', 'stimLocsY1']]*rad_deg

In [39]:
export_data[26:52,0:2] = db[(db['Subject']=='s_03001') & (db['null2'] == 0)][['stimLocsX2', 'stimLocsY2']]*rad_deg

In [40]:
export_data[52:,0:2] = db[(db['Subject']=='s_03001') & (db['null3'] == 0)][['stimLocsX3', 'stimLocsY3']]*rad_deg

In [42]:
export_data[:26,2] = db[(db['Subject']=='s_03001') & (db['null1'] == 0)]['Condition1']

In [43]:
export_data[26:52,2] = db[(db['Subject']=='s_03001') & (db['null2'] == 0)]['Condition2']

In [44]:
export_data[52:,2] = db[(db['Subject']=='s_03001') & (db['null3'] == 0)]['Condition3']

In [45]:
export_data

array([[ -1.46571 ,   0.      ,   3.      ],
       [  0.      ,   3.5784  ,  11.      ],
       [  3.39195 ,   0.      ,   5.      ],
       [  4.89795 ,   0.      ,   6.      ],
       [ -3.14865 ,   0.      ,   2.      ],
       [  0.      ,  -4.2546  ,   7.      ],
       [  0.      ,  -2.53425 ,   8.      ],
       [ -5.19135 ,   0.      ,   1.      ],
       [  0.      ,   0.      ,  13.      ],
       [  0.      ,  -2.2356  ,   9.      ],
       [  2.1522  ,   0.      ,   4.      ],
       [  0.      ,   4.3653  ,  12.      ],
       [  0.      ,   1.8543  ,  10.      ],
       [  0.      ,   1.9659  ,  10.      ],
       [  3.54015 ,   0.      ,   5.      ],
       [  0.      ,  -1.083075,   9.      ],
       [ -0.92316 ,   0.      ,   3.      ],
       [  0.      ,  -2.47005 ,   8.      ],
       [  4.13955 ,   0.      ,   6.      ],
       [  0.      ,   5.11215 ,  12.      ],
       [ -4.3563  ,   0.      ,   1.      ],
       [  0.      ,   0.      ,  13.      ],
       [ -2.6916  ,   0.      ,   2.      ],
       [  0.973545,   0.      ,   4.      ],
       [  0.      ,   2.95965 ,  11.      ],
       [  0.      ,  -4.75275 ,   7.      ],
       [ -2.65545 ,   0.      ,   2.      ],
       [  4.92465 ,   0.      ,   6.      ],
       [ -1.88295 ,   0.      ,   3.      ],
       [  0.      ,   5.2146  ,  12.      ],
       [  3.25215 ,   0.      ,   5.      ],
       [ -3.90675 ,   0.      ,   1.      ],
       [  0.      ,  -4.44015 ,   7.      ],
       [  1.50165 ,   0.      ,   4.      ],
       [  0.      ,   2.9904  ,  11.      ],
       [  0.      ,   1.20708 ,  10.      ],
       [  0.      ,  -3.15015 ,   8.      ],
       [  0.      ,  -2.11335 ,   9.      ],
       [  0.      ,   0.      ,  13.      ],
       [  0.      ,  -0.778215,   9.      ],
       [  0.      ,   2.48565 ,  11.      ],
       [  0.      ,   1.98795 ,  10.      ],
       [ -1.11309 ,   0.      ,   3.      ],
       [  3.2148  ,   0.      ,   5.      ],
       [  0.      ,  -3.0156  ,   8.      ],
       [  4.36785 ,   0.      ,   6.      ],
       [  0.      ,   0.      ,  13.      ],
       [  2.00685 ,   0.      ,   4.      ],
       [ -2.6304  ,   0.      ,   2.      ],
       [ -4.0974  ,   0.      ,   1.      ],
       [  0.      ,   4.28655 ,  12.      ],
       [  0.      ,  -4.0518  ,   7.      ],
       [ -4.01265 ,   0.      ,   1.      ],
       [  0.      ,  -3.5883  ,   8.      ],
       [  0.      ,   1.79265 ,  10.      ],
       [  0.      ,   4.63365 ,  12.      ],
       [ -2.4135  ,   0.      ,   2.      ],
       [  0.      ,  -4.47615 ,   7.      ],
       [  0.      ,   0.      ,  13.      ],
       [  4.73325 ,   0.      ,   6.      ],
       [  1.9509  ,   0.      ,   4.      ],
       [ -1.06788 ,   0.      ,   3.      ],
       [  0.      ,   2.3772  ,  11.      ],
       [  2.59245 ,   0.      ,   5.      ],
       [  0.      ,  -1.05186 ,   9.      ],
       [ -3.3195  ,   0.      ,   2.      ],
       [  1.20717 ,   0.      ,   4.      ],
       [  3.0852  ,   0.      ,   5.      ],
       [ -3.86745 ,   0.      ,   1.      ],
       [  0.      ,   0.      ,  13.      ],
       [  0.      ,   3.22395 ,  11.      ],
       [  0.      ,  -2.9484  ,   8.      ],
       [  0.      ,   1.5288  ,  10.      ],
       [  0.      ,  -3.8343  ,   7.      ],
       [  0.      ,  -1.76565 ,   9.      ],
       [  4.8504  ,   0.      ,   6.      ],
       [  0.      ,   3.969   ,  12.      ],
       [ -1.45698 ,   0.      ,   3.      ]])

In [46]:
from scipy.io import savemat

In [47]:
outname = 'trn_cond'
outpath = outpath = '/fMRI/NLine-Space/s_03001/Peter_ROI_IEM/'
outpathname = outpath+outname

In [48]:
savemat(outpathname,{'trn_cond':export_data})

## Now for test data

In [49]:
test_data = np.zeros((len(db[(db['Subject']=='s_03001') & (db['null4'] == 0)][['stimLocsX4', 'stimLocsY4']]),3))

In [51]:
test_data[:,0:2] = db[(db['Subject']=='s_03001') & (db['null4'] == 0)][['stimLocsX4', 'stimLocsY4']]*rad_deg

In [52]:
test_data[:,2] = db[(db['Subject']=='s_03001') & (db['null4'] == 0)]['Condition4']

In [53]:
test_data

array([[  4.4034  ,   0.      ,   6.      ],
       [  0.      ,  -1.25814 ,   9.      ],
       [  0.      ,   4.1568  ,  12.      ],
       [ -3.25155 ,   0.      ,   2.      ],
       [  0.      ,   3.105   ,  11.      ],
       [  0.      ,   0.      ,  13.      ],
       [  0.      ,  -3.86805 ,   7.      ],
       [  2.6469  ,   0.      ,   5.      ],
       [ -5.13075 ,   0.      ,   1.      ],
       [  2.0976  ,   0.      ,   4.      ],
       [  0.      ,  -2.6694  ,   8.      ],
       [  0.      ,   1.9545  ,  10.      ],
       [ -2.12715 ,   0.      ,   3.      ],
       [  4.43775 ,   0.      ,   6.      ],
       [ -0.950625,   0.      ,   3.      ],
       [  0.      ,   3.2859  ,  11.      ],
       [  0.      ,  -2.2227  ,   9.      ],
       [ -4.94085 ,   0.      ,   1.      ],
       [  0.      ,   0.      ,  13.      ],
       [  0.      ,  -4.5516  ,   7.      ],
       [  0.      ,   1.7616  ,  10.      ],
       [  0.      ,   4.1817  ,  12.      ],
       [  2.1147  ,   0.      ,   4.      ],
       [  0.      ,  -2.58345 ,   8.      ],
       [ -3.5166  ,   0.      ,   2.      ],
       [  2.4318  ,   0.      ,   5.      ]])

In [54]:
outname = 'tst_cond'
outpath = outpath = '/fMRI/NLine-Space/s_03001/Peter_ROI_IEM/'
outpathname = outpath+outname

In [55]:
savemat(outpathname,{'tst_cond':test_data})